import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterMainLayout from "@/components/footer";
import HeaderMainLayout from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        data-theme='aqua'
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderMainLayout />
        <main className='pt-24'>{children}</main>
        <FooterMainLayout />
      </body>
    </html>
  );
}
